### ISSUE TITLE
Pulls used usernames

### ISSUE THREAD

**Issue by thatonehen** [Dhirk07/Roblox-Username-generator#6]
For some reason, it's giving me usernames that are taken (e.g, jmfpn) but i fixed it.
Use this `if not a.find('{"success":false,"errorMessage":"User not found"}') == -1:` instead of `if a.find('Id') == -1:`.
I do not know why this works, but it does.

**Comment by Dhirk07** [comment]
Thanks for fixing this issue, gonna update this repo with credits.
