### ISSUE TITLE
discord_webhook isn't a package...

### ISSUE THREAD

**Issue by ToxicSodapop** [Dhirk07/Roblox-Username-generator#7]
ERROR: Could not find a version that satisfies the requirement DiscordEmbed (from versions: none)
ERROR: No matching distribution found for DiscordEmbed

**Comment by Dhirk07** [comment]
upgrade your pip also use the latest version of python

**Comment by Dhirk07** [comment]
gotta update the code

**Comment by Dhirk07** [comment]
Its already fixed
